<a href="https://colab.research.google.com/github/JoaoAntoni07/estudo-catijr/blob/main/semana-02/semana02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Semana 02

## Numpy

In [1]:
!pip install numpy

In [2]:
import numpy as np

### Array Numpy

In [ ]:
#criar um aarray numpy
array1 = np.array([1,2,3,4,5,6])
print(array1)
print(type(array1))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [ ]:
# array com 2 dimensoes
array2 = np.array([[1,2,3,4],[5,6,7,8]])
print(array2)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
# array com 3 dimenensoes
array3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# criando array vom n dimensoes
array4 = np.array([1,2,3], ndmin=7)
print(array4)

[[[[[[[1 2 3]]]]]]]


In [ ]:
# verificando número de dimensões do array
print(array4.ndim)

7


In [ ]:
# NP arange - criar array de 0 a 20
array5 = np.arange(0,21)
print(array5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
# criando arrayb de 2 a 10
array6 = np.arange(2, 11, 2)
print(array6)

[ 2  4  6  8 10]


In [ ]:
# np.linspace
array7 = np.linspace(0, 100, 5)
print(array7)

[  0.  25.  50.  75. 100.]


In [ ]:
# criar array contendo 5 zeros
array_zeros = np.zeros(5)
print(array_zeros)

#criar matriz de zeros
matriz_zeros = np.zeros([3, 4])
print(matriz_zeros)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Atributos de Numpy

In [ ]:
# dtype
array = np.array([2,3,4,6.77,6.99])
print(array.dtype)

float64


In [ ]:
#shape
array_2_dimensoes = np.array([[1,2,3], [4,5,6]])
print(array_2_dimensoes)
print(array_2_dimensoes.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
# size
print(array_2_dimensoes.size)

6


In [ ]:
# ndim
print(array_2_dimensoes.ndim)

2


In [ ]:
# conversão de arrays
array_float = np.array([1.2,2.3,3.4,4.5])
array_int = np.array([1,2,3,4])
print(array_float)
print(array_float.dtype)

#cast
array_cast = array_float.astype(int)
print(array_cast)
print(array_cast.dtype)

[1.2 2.3 3.4 4.5]
float64
[1 2 3 4]
int64


### Operação com arrays

In [ ]:
# operacções aritmétricas
#som
array1 = np.array([1,2,3,4])
array2 = np.array([4,5,6,7])
array_aux = array1 + array2
print(array_aux)

#subtração
array1 = np.array([1,2,3,4])
array2 = np.array([4,5,6,7])
array_aux = array1 - array2
print(array_aux)

#produto
array1 = np.array([1,2,3,4])
array2 = np.array([4,5,6,7])
array_aux = array1 * array2
print(array_aux)

#divisão
array1 = np.array([1,2,3,4])
array2 = np.array([4,5,6,7])
array_aux = array1 / array2
print(array_aux)

[ 5  7  9 11]
[-3 -3 -3 -3]
[ 4 10 18 28]
[0.25       0.4        0.5        0.57142857]


In [ ]:
# operação com escalar
#soma
array_aux = array2 + 5
print(array_aux)

#subtração
array_aux = array2 - 5
print(array_aux)

#produto
array_aux = array2 * 5
print(array_aux)

#divisão
array_aux = array2 / 5
print(array_aux)

[ 9 10 11 12]
[-1  0  1  2]
[20 25 30 35]
[0.8 1.  1.2 1.4]


In [ ]:
# broadcasting
array1 = np.array([[10,11,13],[15,16,17]])
print(array1)
array2 = np.array([10,20,30])
print(array2)

soma = array1 + array2
print(soma)

[[10 11 13]
 [15 16 17]]
[10 20 30]
[[20 31 43]
 [25 36 47]]


### Funções de agregação

In [ ]:
# sum
soma = array1.sum()
print(soma)

82


In [ ]:
# mean - media aritmétrica
media = array1.mean()
print(media)

13.666666666666666


In [ ]:
# std - calcula desvio padrão dos elementos
dp = array2.std()
print(dp)

8.16496580927726


In [ ]:
# min
valor_min = array1.min()
print(valor_min)

10


In [ ]:
#max
valor_max = array2.max()
print(valor_max)

30


In [ ]:
# por linha e coluna
min_linha = array1.min(axis=1)
max_coluna = array1.max(axis=0)
print(min_linha, max_coluna)

[10 15] [15 16 17]


In [ ]:
# argmax
indice_maior_valor = array1.argmax()
print(indice_maior_valor)

5


### Operações lógicas e comparações

In [ ]:
# igualdade
array1 == array2

array([[ True, False, False],
       [False, False, False]])

In [ ]:
# >/<
array1 < array2

array([[False,  True,  True],
       [False,  True,  True]])

In [ ]:
array1 >= array2

array([[ True, False, False],
       [ True, False, False]])

In [ ]:
# operadores lógicos
array_bool = np.array([True, False, True])
array_bool2 = np.array([False, False,True])

#and
array_and = array_bool & array_bool2
print(array_and)

#or
array_or = array_bool | array_bool2
print(array_or)

[False False  True]
[ True False  True]


In [ ]:
# filtragem
dados = np.array([1,2,3,4,5,6,7])

filtro = dados < 5
print(filtro)

[ True  True  True  True False False False]


### Indexação e fatiamento

In [ ]:
# fatiamento
# acessando elementos
array = np.arange(10, 60, 10)
print(array)

print(array[0])
print(array[2])

#matriz
matriz = np.array([[1,2,4],[6,7,3],[8,9,4]])
print(matriz)
#acessando elemento da matriz
print(matriz[0, 1])

[10 20 30 40 50]
10
30
[[1 2 4]
 [6 7 3]
 [8 9 4]]
2


In [ ]:
# fatiamento [inicial, final -1:passo]
array = np.arange(0,9)
print(array)

fat = array[2:6:1]
print(fat)

# matriz
matriz = np.array([[10, 20, 30], [40, 50, 60]])
print(matriz)
# acessar todas as linhas mas somente coluna 1 e 2
fat = matriz[:, 1:3]
print(fat)

[0 1 2 3 4 5 6 7 8]
[2 3 4 5]
[[10 20 30]
 [40 50 60]]
[[20 30]
 [50 60]]


In [ ]:
# indexação booleana
dados = np.arange(1, 11)
print(dados)

# criando uma condição
condicao = dados > 5
print(condicao)

elementos = dados[condicao]
print(elementos)

[ 1  2  3  4  5  6  7  8  9 10]
[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]


In [ ]:
# elementos pares e maiores que 5
condicao1 = dados % 2 == 0
condicao2 = dados > 5
elementos = dados[condicao1 & condicao2]
print(elementos)


[ 6  8 10]


## Panda

In [2]:
!pip install pandas

In [3]:
import pandas as pd

### Séries

In [6]:
# criando uma series a partir de uma lista
numeros = [10, 20, 30, 40, 50]

serie1 = pd.Series(numeros)
print(serie1)
print(type(serie1))

0    10
1    20
2    30
3    40
4    50
dtype: int64
<class 'pandas.core.series.Series'>


In [7]:
# acessar um elemento da serie
print(serie1[2])

30


In [9]:
# criar uma serie com indice personalizado
lista_numeros = [100, 200, 300]
index = ['a', 'b', 'c']

serie_personalizada = pd.Series(lista_numeros, index)
print(serie_personalizada)
print(serie_personalizada['a'])

a    100
b    200
c    300
dtype: int64
100


In [11]:
# criar uma serie a partir de um dicionario
dados = {'primeiro' : 1, 'segundo' : 2, 'terceiro' : 3}
print(dados)

serie_dic = pd.Series(dados)
print(serie_dic)

{'primeiro': 1, 'segundo': 2, 'terceiro': 3}
primeiro    1
segundo     2
terceiro    3
dtype: int64


### Dataframes

In [15]:
# criando dataframe a partir de um dicionario
dados = {
    'Nome' : ['Leo', 'José', 'Marcelo'],
    'Idade' : [25, 30,19],
    'Cidade' : ['Rio Preto', 'Bauru', 'Jaú']
}
df = pd.DataFrame(dados)
print(df)

      Nome  Idade     Cidade
0      Leo     25  Rio Preto
1     José     30      Bauru
2  Marcelo     19        Jaú


In [17]:
# acessando uma coluna específica do dataframe
print(df.Nome)
print(df['Idade'])

0        Leo
1       José
2    Marcelo
Name: Nome, dtype: object
0    25
1    30
2    19
Name: Idade, dtype: int64


In [18]:
# criar um dataframe a partir de uma lista de dicionarios
lista_dict = [
    {'Nome' : 'Rodrigo', 'Idade' : 28, 'Cidade' : 'São Paulo'},
    {'Nome' : 'João', 'Idade' : 21, 'Cidade' : 'Botucatu'},
    {'Nome' : 'Marcela', 'Idade' : 22, 'Cidade' : 'Campinas'}
]

df2 = pd.DataFrame(lista_dict)
print(df2)

      Nome  Idade     Cidade
0  Rodrigo     28  São Paulo
1     João     21   Botucatu
2  Marcela     22   Campinas


### Ler e salvar

In [21]:
# leitura de arquivos csv
url = 'https://raw.githubusercontent.com/plotly/datasets/master/gapminderDataFiveYear.csv'

df = pd.read_csv(url)
print(df)

          country  year         pop continent  lifeExp   gdpPercap
0     Afghanistan  1952   8425333.0      Asia   28.801  779.445314
1     Afghanistan  1957   9240934.0      Asia   30.332  820.853030
2     Afghanistan  1962  10267083.0      Asia   31.997  853.100710
3     Afghanistan  1967  11537966.0      Asia   34.020  836.197138
4     Afghanistan  1972  13079460.0      Asia   36.088  739.981106
...           ...   ...         ...       ...      ...         ...
1699     Zimbabwe  1987   9216418.0    Africa   62.351  706.157306
1700     Zimbabwe  1992  10704340.0    Africa   60.377  693.420786
1701     Zimbabwe  1997  11404948.0    Africa   46.809  792.449960
1702     Zimbabwe  2002  11926563.0    Africa   39.989  672.038623
1703     Zimbabwe  2007  12311143.0    Africa   43.487  469.709298

[1704 rows x 6 columns]


In [ ]:
# ler arquivos xlsx
df2 = pd.read_excel('exemplo.xlsx')

In [22]:
# salvar no formato csv
df3 = pd.DataFrame({
    'Frutas' : ['Maçã', 'Banana', 'Pera'],
    'Quantidade' : [100, 140, 70]
})

df3.to_csv('frutas.csv', index=False)

In [24]:
df4 = pd.read_csv('frutas.csv')
print(df4)

   Frutas  Quantidade
0    Maçã         100
1  Banana         140
2    Pera          70


### Head, tail, shape, info e describe

In [25]:
# criando um dataframe
dados = {
    'Nome' : ['Leo', 'José', 'Marcelo'],
    'Idade' : [25, 30,19],
    'Cidade' : ['Rio Preto', 'Bauru', 'Jaú']
}

df = pd.DataFrame(dados)
print(df)

      Nome  Idade     Cidade
0      Leo     25  Rio Preto
1     José     30      Bauru
2  Marcelo     19        Jaú


In [27]:
# head(n) -  retorna as primeiras n linhas, por padrão retorna 5 se tiver
print(df.head(1))

  Nome  Idade     Cidade
0  Leo     25  Rio Preto


In [28]:
# tail(n) - retorna as últimas n linhas
print(df.tail(1))

      Nome  Idade Cidade
2  Marcelo     19    Jaú


In [32]:
# shape  - retorna linhas e colunas
df.shape

(3, 3)

In [33]:
# info - fornece um resumo do dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Nome    3 non-null      object
 1   Idade   3 non-null      int64 
 2   Cidade  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes


In [34]:
# describe() - retorna estatísticas sobre o dataframe
print(df.describe())

           Idade
count   3.000000
mean   24.666667
std     5.507571
min    19.000000
25%    22.000000
50%    25.000000
75%    27.500000
max    30.000000


### Loc e iloc

In [35]:
# criar df
dados = {
    'Produto' : ['A', 'B', 'C', 'D', 'E'],
    'Preco' : [10.3, 20.0, 15.75, 30.0, 25.25],
    'Estoque' : [100, 50, 75, 20, 90]
}

index = ['item1', 'item2', 'item3', 'item4', 'item5']

df = pd.DataFrame(dados, index)
print(df)

      Produto  Preco  Estoque
item1       A  10.30      100
item2       B  20.00       50
item3       C  15.75       75
item4       D  30.00       20
item5       E  25.25       90


In [36]:
# visualizar colunas especificas
df.Produto
df['Estoque']

,Produto
item1,A
item2,B
item3,C
item4,D
item5,E


In [37]:
# selecionar multiplas colunas
print(df[['Produto', 'Estoque']])

      Produto  Estoque
item1       A      100
item2       B       50
item3       C       75
item4       D       20
item5       E       90


In [40]:
# loc - seleção do item 2
print(df.loc['item2'])

Produto       B
Preco      20.0
Estoque      50
Name: item2, dtype: object


In [41]:
# retornando linhas e colunas
print(df.loc[['item1', 'item5'], ['Preco', 'Estoque']])

       Preco  Estoque
item1  10.30      100
item5  25.25       90


In [42]:
# comando iloc para buscar o item3
print(df.iloc[2])

Produto        C
Preco      15.75
Estoque       75
Name: item3, dtype: object


In [43]:
# comando iloc para linhas e colunas
print(df.iloc[0:2, 1:3])

       Preco  Estoque
item1   10.3      100
item2   20.0       50


### Filtrando dados

In [44]:
# criar o dataframe
dados = {
    'Produto' : ['A', 'B', 'C', 'D', 'E'],
    'Preco' : [10.3, 20.0, 15.75, 30.0, 25.25],
    'Estoque' : [100, 50, 75, 20, 90]
}
df = pd.DataFrame(dados)
print(df)

  Produto  Preco  Estoque
0       A  10.30      100
1       B  20.00       50
2       C  15.75       75
3       D  30.00       20
4       E  25.25       90


In [45]:
# filtrar produtos com preço maior que 25
filtro_preco = df[df.Preco > 25]
print(filtro_preco)

  Produto  Preco  Estoque
3       D  30.00       20
4       E  25.25       90


In [46]:
# filtro preço < 30 e estoque > 60
filtro2 = df[(df.Preco < 30) & (df.Estoque > 60)]
print(filtro2)

  Produto  Preco  Estoque
0       A  10.30      100
2       C  15.75       75
4       E  25.25       90


### Sort values

In [5]:
dados = {
    'Produto' : ['Maçã', 'Banana', 'Laranja', 'Uva', 'Pera'],
    'Preco' : [10.3, 20.0, 15.75, 30.0, 25.25],
    'Estoque' : [100, 50, 75, 20, 90]
}
df = pd.DataFrame(dados)
print(df)

   Produto  Preco  Estoque
0     Maçã  10.30      100
1   Banana  20.00       50
2  Laranja  15.75       75
3      Uva  30.00       20
4     Pera  25.25       90


In [6]:
# ordenar por preço em ordem crescente
df_preco = df.sort_values(by='Preco')
print(df_preco)

   Produto  Preco  Estoque
0     Maçã  10.30      100
2  Laranja  15.75       75
1   Banana  20.00       50
4     Pera  25.25       90
3      Uva  30.00       20


In [10]:
# ordem decrescente
df_quantidade = df.sort_values(by='Estoque', ascending=False)
print(df_quantidade)

   Produto  Preco  Estoque
0     Maçã  10.30      100
4     Pera  25.25       90
2  Laranja  15.75       75
1   Banana  20.00       50
3      Uva  30.00       20


In [11]:
df_multi = df.sort_values(by=['Preco', 'Estoque'], ascending=False)
print(df_multi)

   Produto  Preco  Estoque
3      Uva  30.00       20
4     Pera  25.25       90
1   Banana  20.00       50
2  Laranja  15.75       75
0     Maçã  10.30      100


### Formatando colunas

In [13]:
dados = {
    'Produto' : ['Maçã', 'Banana', 'Laranja', 'Uva', 'Pera'],
    'Preco' : [10.3, 20.0, 15.75, 30.0, 25.25],
    'Quantidade_vendida' : [100, 50, 75, 20, 90]
}
df = pd.DataFrame(dados)
print(df)

   Produto  Preco  Quantidade_vendida
0     Maçã  10.30                 100
1   Banana  20.00                  50
2  Laranja  15.75                  75
3      Uva  30.00                  20
4     Pera  25.25                  90


In [15]:
# criar uma nova coluna
df['Valor_total'] = df['Preco'] * df['Quantidade_vendida']
print(df)

   Produto  Preco  Quantidade_vendida  Valor_total
0     Maçã  10.30                 100      1030.00
1   Banana  20.00                  50      1000.00
2  Laranja  15.75                  75      1181.25
3      Uva  30.00                  20       600.00
4     Pera  25.25                  90      2272.50


In [16]:
# coluna com valor fixo
df['Desconto_aplicado'] = 0.10
print(df)

   Produto  Preco  Quantidade_vendida  Valor_total  Desconto_aplicado
0     Maçã  10.30                 100      1030.00                0.1
1   Banana  20.00                  50      1000.00                0.1
2  Laranja  15.75                  75      1181.25                0.1
3      Uva  30.00                  20       600.00                0.1
4     Pera  25.25                  90      2272.50                0.1


In [20]:
# renomear coluna
df_novo = df.rename(columns={'Produto' : 'Produto_loja'})
print(df_novo)

  Produto_loja  Preco  Quantidade_vendida  Valor_total  Desconto_aplicado
0         Maçã  10.30                 100      1030.00                0.1
1       Banana  20.00                  50      1000.00                0.1
2      Laranja  15.75                  75      1181.25                0.1
3          Uva  30.00                  20       600.00                0.1
4         Pera  25.25                  90      2272.50                0.1


In [21]:
# remover colunas
df = df.drop('Desconto_aplicado', axis=1)
print(df)

   Produto  Preco  Quantidade_vendida  Valor_total
0     Maçã  10.30                 100      1030.00
1   Banana  20.00                  50      1000.00
2  Laranja  15.75                  75      1181.25
3      Uva  30.00                  20       600.00
4     Pera  25.25                  90      2272.50


### Astype, Isna, Fillna e Dropna

In [22]:
import numpy as np

In [23]:
# criar o DF
dados = {
    'Numero_string' : ['1', '2', '3', '4'],
    'Preco_float' : [10.5, 20.0, 15.75, 30.0]
}
df = pd.DataFrame(dados)
print(df)

  Numero_string  Preco_float
0             1        10.50
1             2        20.00
2             3        15.75
3             4        30.00


In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Numero_string  4 non-null      object 
 1   Preco_float    4 non-null      float64
dtypes: float64(1), object(1)
memory usage: 196.0+ bytes


In [27]:
# converter string para int
df['Numero_string'] = df['Numero_string'].astype(int)
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Numero_string  4 non-null      int64  
 1   Preco_float    4 non-null      float64
dtypes: float64(1), int64(1)
memory usage: 196.0 bytes
None


In [29]:
# converter preco para int
df['Preco_float'] = df['Preco_float'].astype(int)
print(df.info())
print(df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Numero_string  4 non-null      int64
 1   Preco_float    4 non-null      int64
dtypes: int64(2)
memory usage: 196.0 bytes
None
   Numero_string  Preco_float
0              1           10
1              2           20
2              3           15
3              4           30


In [32]:
df2 = pd.DataFrame({
    'A' : [1, 2, np.nan, 4, 5],
    'B' : [np.nan, 2, 3, 4, np.nan],
    'C' : [1, 2, 3, 4, 5]
})
print(df2)

     A    B  C
0  1.0  NaN  1
1  2.0  2.0  2
2  NaN  3.0  3
3  4.0  4.0  4
4  5.0  NaN  5


In [33]:
# isna()
print(df2.isna())

       A      B      C
0  False   True  False
1  False  False  False
2   True  False  False
3  False  False  False
4  False   True  False


In [34]:
# fillna - preencher com 0 onde temos valores nulos
df_nulos = df2.fillna({'A' : 0})
print(df_nulos)

     A    B  C
0  1.0  NaN  1
1  2.0  2.0  2
2  0.0  3.0  3
3  4.0  4.0  4
4  5.0  NaN  5


In [35]:
# fillna - preencher com a media de valores
df_media = df2.fillna(df2.mean())
print(df_media)

     A    B  C
0  1.0  3.0  1
1  2.0  2.0  2
2  3.0  3.0  3
3  4.0  4.0  4
4  5.0  3.0  5


In [36]:
# remover linhas com valores ausentes
df_drop_linhas = df2.dropna()
print(df_drop_linhas)

     A    B  C
1  2.0  2.0  2
3  4.0  4.0  4


### Apply e map

In [40]:
# criar o df
dados = {
    'Nome' : ['Leo', 'José', 'Marcelo'],
    'Idade' : [25, 31, 19],
    'Status' : ['ativo', 'inativo', 'ativo']
}
df = pd.DataFrame(dados)
print(df)

      Nome  Idade   Status
0      Leo     25    ativo
1     José     31  inativo
2  Marcelo     19    ativo


In [42]:
# apply
def categoria_idade(idade):
    if idade < 30:
        return 'Jovem'
    else:
        return 'Adulto'

df['Categorai_idade'] = df['Idade'].apply(categoria_idade)
print(df)

      Nome  Idade   Status Categorai_idade
0      Leo     25    ativo           Jovem
1     José     31  inativo          Adulto
2  Marcelo     19    ativo           Jovem


In [45]:
# map
mapeamento_status = {'ativo' : 'Ativo', 'inativo' : 'Inativo'}
df['Status_formatado'] = df['Status'].map(mapeamento_status)
print(df)

      Nome  Idade   Status Categorai_idade Status_formatado
0      Leo     25    ativo           Jovem            Ativo
1     José     31  inativo          Adulto          Inativo
2  Marcelo     19    ativo           Jovem            Ativo


### Funções de agragação

In [50]:
dados = {
    'Cidade' : ['São Paulo', 'Rio de Janeiro', 'São Paulo', 'Belo Horizonte', 'Rio de Janeiro', 'São Paulo'],
    'Vendas' : [100, 150, 120, 80, 200, 90],
    'Produto' : ['A', 'B', 'A', 'C', 'B', 'A']
}
df = pd.DataFrame(dados)
print(df)

           Cidade  Vendas Produto
0       São Paulo     100       A
1  Rio de Janeiro     150       B
2       São Paulo     120       A
3  Belo Horizonte      80       C
4  Rio de Janeiro     200       B
5       São Paulo      90       A


In [51]:
# agrupar por cidade e calcular soma das vendas por cidade
vendas_por_cidade = df.groupby('Cidade')['Vendas'].sum()
print(vendas_por_cidade)

Cidade
Belo Horizonte     80
Rio de Janeiro    350
São Paulo         310
Name: Vendas, dtype: int64


In [53]:
media_vendas = df.groupby(['Cidade', 'Produto'])['Vendas'].mean()
print(media_vendas)

Cidade          Produto
Belo Horizonte  C           80.000000
Rio de Janeiro  B          175.000000
São Paulo       A          103.333333
Name: Vendas, dtype: float64


### Funções de data

In [54]:
df_datas = pd.DataFrame({
    'Data_string' : ['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04'],
    'Evento' : ['Feriado', 'Reunião', 'Lançamento', 'Manutenção']
})
print(df_datas)

  Data_string      Evento
0  2023-01-01     Feriado
1  2023-01-02     Reunião
2  2023-01-03  Lançamento
3  2023-01-04  Manutenção


In [55]:
# dtypes
print(df_datas.dtypes)

Data_string    object
Evento         object
dtype: object


In [57]:
# converter data_string para datetime
df_datas['Data'] = pd.to_datetime(df_datas['Data_string'])
print(df_datas)
print(df_datas.dtypes)

  Data_string      Evento       Data
0  2023-01-01     Feriado 2023-01-01
1  2023-01-02     Reunião 2023-01-02
2  2023-01-03  Lançamento 2023-01-03
3  2023-01-04  Manutenção 2023-01-04
Data_string            object
Evento                 object
Data           datetime64[ns]
dtype: object


In [58]:
df_datas_formato = pd.DataFrame({
    'Data' : ['01/01/2023', '02-Jan-2023', '20230103'],
    'Valor' : [10, 20, 30]
})
print(df_datas_formato)

          Data  Valor
0   01/01/2023     10
1  02-Jan-2023     20
2     20230103     30


In [60]:
df_datas_formato['Data_convertida'] = pd.to_datetime(df_datas_formato['Data'], format = 'mixed')
print(df_datas_formato)

          Data  Valor Data_convertida
0   01/01/2023     10      2023-01-01
1  02-Jan-2023     20      2023-01-02
2     20230103     30      2023-01-03
