<a href="https://colab.research.google.com/github/JoaoAntoni07/estudo-catijr/blob/main/semana-02/semana02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Semana 02

## Numpy

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

### Array Numpy

In [ ]:
#criar um aarray numpy
array1 = np.array([1,2,3,4,5,6])
print(array1)
print(type(array1))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [ ]:
# array com 2 dimensoes
array2 = np.array([[1,2,3,4],[5,6,7,8]])
print(array2)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
# array com 3 dimenensoes
array3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# criando array vom n dimensoes
array4 = np.array([1,2,3], ndmin=7)
print(array4)

[[[[[[[1 2 3]]]]]]]


In [ ]:
# verificando número de dimensões do array
print(array4.ndim)

7


In [ ]:
# NP arange - criar array de 0 a 20
array5 = np.arange(0,21)
print(array5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
# criando arrayb de 2 a 10
array6 = np.arange(2, 11, 2)
print(array6)

[ 2  4  6  8 10]


In [ ]:
# np.linspace
array7 = np.linspace(0, 100, 5)
print(array7)

[  0.  25.  50.  75. 100.]


In [ ]:
# criar array contendo 5 zeros
array_zeros = np.zeros(5)
print(array_zeros)

#criar matriz de zeros
matriz_zeros = np.zeros([3, 4])
print(matriz_zeros)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Atributos de Numpy

In [ ]:
# dtype
array = np.array([2,3,4,6.77,6.99])
print(array.dtype)

float64


In [ ]:
#shape
array_2_dimensoes = np.array([[1,2,3], [4,5,6]])
print(array_2_dimensoes)
print(array_2_dimensoes.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
# size
print(array_2_dimensoes.size)

6


In [ ]:
# ndim
print(array_2_dimensoes.ndim)

2


In [ ]:
# conversão de arrays
array_float = np.array([1.2,2.3,3.4,4.5])
array_int = np.array([1,2,3,4])
print(array_float)
print(array_float.dtype)

#cast
array_cast = array_float.astype(int)
print(array_cast)
print(array_cast.dtype)

[1.2 2.3 3.4 4.5]
float64
[1 2 3 4]
int64


### Operação com arrays

In [ ]:
# operacções aritmétricas
#som
array1 = np.array([1,2,3,4])
array2 = np.array([4,5,6,7])
array_aux = array1 + array2
print(array_aux)

#subtração
array1 = np.array([1,2,3,4])
array2 = np.array([4,5,6,7])
array_aux = array1 - array2
print(array_aux)

#produto
array1 = np.array([1,2,3,4])
array2 = np.array([4,5,6,7])
array_aux = array1 * array2
print(array_aux)

#divisão
array1 = np.array([1,2,3,4])
array2 = np.array([4,5,6,7])
array_aux = array1 / array2
print(array_aux)

[ 5  7  9 11]
[-3 -3 -3 -3]
[ 4 10 18 28]
[0.25       0.4        0.5        0.57142857]


In [ ]:
# operação com escalar
#soma
array_aux = array2 + 5
print(array_aux)

#subtração
array_aux = array2 - 5
print(array_aux)

#produto
array_aux = array2 * 5
print(array_aux)

#divisão
array_aux = array2 / 5
print(array_aux)

[ 9 10 11 12]
[-1  0  1  2]
[20 25 30 35]
[0.8 1.  1.2 1.4]


In [ ]:
# broadcasting
array1 = np.array([[10,11,13],[15,16,17]])
print(array1)
array2 = np.array([10,20,30])
print(array2)

soma = array1 + array2
print(soma)

[[10 11 13]
 [15 16 17]]
[10 20 30]
[[20 31 43]
 [25 36 47]]


### Funções de agregação

In [ ]:
# sum
soma = array1.sum()
print(soma)

82


In [ ]:
# mean - media aritmétrica
media = array1.mean()
print(media)

13.666666666666666


In [ ]:
# std - calcula desvio padrão dos elementos
dp = array2.std()
print(dp)

8.16496580927726


In [ ]:
# min
valor_min = array1.min()
print(valor_min)

10


In [ ]:
#max
valor_max = array2.max()
print(valor_max)

30


In [ ]:
# por linha e coluna
min_linha = array1.min(axis=1)
max_coluna = array1.max(axis=0)
print(min_linha, max_coluna)

[10 15] [15 16 17]


In [ ]:
# argmax
indice_maior_valor = array1.argmax()
print(indice_maior_valor)

5


### Operações lógicas e comparações

In [ ]:
# igualdade
array1 == array2

array([[ True, False, False],
       [False, False, False]])

In [ ]:
# >/<
array1 < array2

array([[False,  True,  True],
       [False,  True,  True]])

In [ ]:
array1 >= array2

array([[ True, False, False],
       [ True, False, False]])

In [ ]:
# operadores lógicos
array_bool = np.array([True, False, True])
array_bool2 = np.array([False, False,True])

#and
array_and = array_bool & array_bool2
print(array_and)

#or
array_or = array_bool | array_bool2
print(array_or)

[False False  True]
[ True False  True]


In [ ]:
# filtragem
dados = np.array([1,2,3,4,5,6,7])

filtro = dados < 5
print(filtro)

[ True  True  True  True False False False]


### Indexação e fatiamento

In [ ]:
# fatiamento
# acessando elementos
array = np.arange(10, 60, 10)
print(array)

print(array[0])
print(array[2])

#matriz
matriz = np.array([[1,2,4],[6,7,3],[8,9,4]])
print(matriz)
#acessando elemento da matriz
print(matriz[0, 1])

[10 20 30 40 50]
10
30
[[1 2 4]
 [6 7 3]
 [8 9 4]]
2


In [ ]:
# fatiamento [inicial, final -1:passo]
array = np.arange(0,9)
print(array)

fat = array[2:6:1]
print(fat)

# matriz
matriz = np.array([[10, 20, 30], [40, 50, 60]])
print(matriz)
# acessar todas as linhas mas somente coluna 1 e 2
fat = matriz[:, 1:3]
print(fat)

[0 1 2 3 4 5 6 7 8]
[2 3 4 5]
[[10 20 30]
 [40 50 60]]
[[20 30]
 [50 60]]


In [ ]:
# indexação booleana
dados = np.arange(1, 11)
print(dados)

# criando uma condição
condicao = dados > 5
print(condicao)

elementos = dados[condicao]
print(elementos)

[ 1  2  3  4  5  6  7  8  9 10]
[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]


In [ ]:
# elementos pares e maiores que 5
condicao1 = dados % 2 == 0
condicao2 = dados > 5
elementos = dados[condicao1 & condicao2]
print(elementos)

[ 6  8 10]
